import Parent from './Parent'
import './App.css'
//script section 

window.addEventListener('resize', () => { 

})
let pages = [{
  name: "home", 
  title: "Welcome to Sol Flower Farm!",
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}, { 
  name: "about", 
  title: "about us",
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Urna neque viverra justo nec ultrices dui. Aliquet enim tortor at auctor urna nunc. Venenatis urna cursus eget nunc scelerisque. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Convallis aenean et tortor at risus viverra adipiscing. Condimentum lacinia quis vel eros donec. In tellus integer feugiat scelerisque varius. Morbi tristique senectus et netus. Duis at tellus at urna condimentum. Faucibus a pellentesque sit amet porttitor. Interdum velit laoreet id donec ultrices tincidunt arcu non. Sit amet massa vitae tortor condimentum lacinia quis vel. Accumsan tortor posuere ac ut. Tellus integer feugiat scelerisque varius. Sed enim ut sem viverra aliquet eget. Semper quis lectus nulla at volutpat diam. Tempor orci dapibus ultrices in iaculis nunc. Ornare arcu odio ut sem nulla pharetra. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Aliquet risus feugiat in ante. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Pulvinar pellentesque habitant morbi tristique senectus et. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. In metus vulputate eu scelerisque. Porttitor rhoncus dolor purus non enim. Vulputate eu scelerisque felis imperdiet. Habitant morbi tristique senectus et netus et. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Elementum integer enim neque volutpat ac tincidunt. Id donec ultrices tincidunt arcu non. Nulla facilisi morbi tempus iaculis. Pellentesque elit eget gravida cum sociis natoque penatibus. Sit amet nisl suscipit adipiscing. Duis convallis convallis tellus id. Gravida rutrum quisque non tellus. Vivamus arcu felis bibendum ut tristique. Etiam erat velit scelerisque in dictum non. Sagittis vitae et leo duis ut diam quam nulla porttitor. Vitae elementum curabitur vitae nunc sed velit. At augue eget arcu dictum. Orci ac auctor augue mauris augue neque. Donec ac odio tempor orci dapibus ultrices."
}, { 
  name: "contact", 
  title: "contact us",
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris. Habitant morbi tristique senectus et netus et malesuada fames. Pharetra massa massa ultricies mi quis. Ipsum a arcu cursus vitae congue mauris rhoncus. Volutpat sed cras ornare arcu dui vivamus arcu felis. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Amet aliquam id diam maecenas ultricies mi eget mauris. Malesuada fames ac turpis egestas sed tempus urna et pharetra. In eu mi bibendum neque egestas congue quisque egestas diam. Volutpat maecenas volutpat blandit aliquam etiam erat. Consectetur libero id faucibus nisl tincidunt eget nullam non. Tellus in metus vulputate eu scelerisque. Amet mattis vulputate enim nulla. Dictum sit amet justo donec enim diam vulputate ut. A cras semper auctor neque vitae tempus. Pretium aenean pharetra magna ac placerat. Nibh venenatis cras sed felis eget. Tortor consequat id porta nibh venenatis. Pellentesque id nibh tortor id aliquet lectus proin nibh. Viverra ipsum nunc aliquet bibendum. Pharetra pharetra massa massa ultricies mi quis hendrerit. At augue eget arcu dictum varius. Enim diam vulputate ut pharetra sit amet aliquam. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Nulla facilisi nullam vehicula ipsum. Nisi vitae suscipit tellus mauris. Tellus elementum sagittis vitae et leo duis ut diam. Sed adipiscing diam donec adipiscing tristique risus nec. Orci a scelerisque purus semper eget duis. Sed tempus urna et pharetra. Amet consectetur adipiscing elit ut. Pellentesque eu tincidunt tortor aliquam. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Quam nulla porttitor massa id neque aliquam vestibulum. Lobortis elementum nibh tellus molestie nunc non. Et malesuada fames ac turpis egestas. Suspendisse potenti nullam ac tortor. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Congue eu consequat ac felis donec et odio pellentesque. Risus in hendrerit gravida rutrum quisque non tellus orci. Quis ipsum suspendisse ultrices gravida dictum fusce. Iaculis eu non diam phasellus vestibulum lorem sed risus."
}, { 
  name: "social", 
  title: "check us out on social media",
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non tellus orci ac auctor augue mauris. Consequat interdum varius sit amet. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Interdum consectetur libero id faucibus. Integer vitae justo eget magna fermentum. Sit amet consectetur adipiscing elit duis tristique. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Laoreet sit amet cursus sit amet dictum. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Elementum curabitur vitae nunc sed velit dignissim. Est velit egestas dui id ornare. Morbi leo urna molestie at elementum eu facilisis sed. Nec nam aliquam sem et tortor consequat. Quis varius quam quisque id. Sit amet risus nullam eget felis eget nunc lobortis mattis. Pharetra diam sit amet nisl suscipit. Ornare arcu dui vivamus arcu felis bibendum ut. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Nibh nisl condimentum id venenatis a condimentum. Porta nibh venenatis cras sed felis. Nibh nisl condimentum id venenatis a condimentum. Aliquam faucibus purus in massa. Cras tincidunt lobortis feugiat vivamus. Massa enim nec dui nunc mattis enim ut tellus. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Sollicitudin aliquam ultrices sagittis orci a. Adipiscing enim eu turpis egestas. Vel pretium lectus quam id leo. Sit amet mattis vulputate enim. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Cursus risus at ultrices mi tempus imperdiet nulla. Sit amet justo donec enim diam vulputate ut pharetra sit. Sapien eget mi proin sed libero enim sed. Massa tincidunt nunc pulvinar sapien. Id aliquet lectus proin nibh nisl condimentum id. Turpis egestas sed tempus urna. Platea dictumst vestibulum rhoncus est pellentesque elit. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Proin sed libero enim sed. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Velit egestas dui id ornare arcu odio. Nibh nisl condimentum id venenatis a."
}]
function App() {  

    return(
    <div> 
      <h1 className = "nav_bar"></h1>
        <Parent curPage = "home" pages = {pages}/> 
      </div>
      )
}

export default App
